### ISSUE TITLE
Not working on React Native

### ISSUE THREAD

**Issue by brunolemos** [gr2m/universal-user-agent#37]
After upgrading `@octokit/rest` from `16.22.0` to `16.43.1` support for react native was broken. The issue seems to come from `universal-user-agent` that is using some node-specific packages.

### First error

`Unable to resolve module `os` from "node_modules/os-name/index.js"`
Cause: https://github.com/gr2m/universal-user-agent/blob/d671405f5c3fc9922a7f61468d8ec694866825a4/src/node.ts#L1

### Second error

`TypeError: undefined is not an object (evaluating 'process.version.substr')`
Cause: https://github.com/gr2m/universal-user-agent/blob/d671405f5c3fc9922a7f61468d8ec694866825a4/src/node.ts#L5 

If you make the react-native target be the same as `web` it will not crash but `navigator.userAgent` is undefined. You can get the `Platform.OS` from `react-native`.

**Comment by gr2m** [comment]
I'm pretty sure it is caused by the same issue as discussed in. https://github.com/gr2m/universal-user-agent/issues/23

Did you find a workaround as reference for other React Native users?

Note that I do not test the Octokit Libraries with React Native at this point. But I will look into it together with other targets such as Electron and Deno, once conditional exports are supported by Pika

**Comment by brunolemos** [comment]
> I'm pretty sure it is caused by the same issue as discussed in. #23

Yeah maybe. React Native is picking the node target.

> Did you find a workaround as reference for other React Native users?

I patched `os-name` using [patch-package](https://github.com/ds300/patch-package#). I created the file `node_modules/os-name/index.native.js`. I also set the value of `process.version` to my app's version.

#### `patches/os-name+3.1.0.patch`

```diff
diff --git a/node_modules/os-name/index.native.js b/node_modules/os-name/index.native.js
new file mode 100644
index 0000000..da50ffc
--- /dev/null
+++ b/node_modules/os-name/index.native.js
@@ -0,0 +1,9 @@
+'use strict';
+
+const { Platform } = require('react-native');
+
+const osName = (platform, release) => {
+	return Platform.OS;
+};
+
+module.exports = osName;
```

#### `index.js`

```js
if (!process.version) {
  process.version = require('@myapp/src/utils/constants').APP_VERSION
}
```

**Comment by gr2m** [comment]
> ```source-js
> if (!process.version) {
>   process.version = require('./package.json').version || ''
> }
> ```

`process.version` is the Node version, not the package version.

I think maybe you can patch the whole package to return a single function which would just return `ReactNative/1.2.3` where `1.2.3` would be the version of the current React Native at build time?

**Comment by brunolemos** [comment]
since I have a monorepo sharing code between `web`, `mobile` and `server` I decided to patch in a way that wouldn't affect the other platforms.

my first attempt was to create `universal-user-agent/dist-node/index.native.js` but for some reason it keeps using the normal `index.js` instead.

but yeah it's probably better to just patch `universal-user-agent` directly, I would just need to keep it working for the other platforms as well

**Comment by gr2m** [comment]
Thanks for sharing Bruno, I'll leave the issue open for others who run into the same problem

**Comment by brunolemos** [comment]
> for some reason it keeps using the normal `index.js` instead of `index.native.js`

Note: Changing the `universal-user-agent/package.json` from `"main": "dist-node/index.js"` to `"main": "dist-node/"` fixes this (but `patch-package` can't package `package.json`).

**Comment by gr2m** [comment]
I'll add a try/catch around the `navigator.userAgent`, so at least it should no longer throw an error, via https://github.com/gr2m/universal-user-agent/pull/41

Once conditional exports are supported by `@pika/pack`, I can provide custom exports for different environments, so the resulting user agent will be more helpful than `<navigator unknown>`, but at least this should unblock people for the time being

Any thoughts?

**Comment by brunolemos** [comment]
`navigator` is available in react native.

The problem is `process.version.substr` and `require('os')`. 

A possible solution is the one from the comment above (change the package.json main entry point to the folder instead file, and create index.native.js)

**Comment by gr2m** [comment]
Ah I see, I'll add a try/catch to `/src/node.ts`, too, until we have proper support for conditional exports. Thanks Bruno!

**Comment by gr2m** [comment]
I've decided to greatly simplify this package to workaround the build problems y'all are experiencing. I was hoping for conditional exports to be adopted more quickly, but it does not look like it.

For React Native, I wonder if there would be a way to get a user agent such as "ReactNative/1.2.3" without importing external dependencies. Any idea?

See https://github.com/gr2m/universal-user-agent/issues/52
