### ISSUE TITLE
Changelog please?

### ISSUE THREAD

**Issue by ramya-rao-a** [gr2m/universal-user-agent#74]
Hello!

We are trying to update our dependency on the `universal-user-agent` package from v6 to v7.
Can you please consider adding a changelog.md file in the root of this repo listing the breaking changes between the two major versions?

**Comment by gr2m** [comment]
Release notes are in the repositories releases:
https://github.com/gr2m/universal-user-agent/releases/tag/v7.0.0

**Comment by ramya-rao-a** [comment]
Thank you!
